In [5]:
import pandas as pd

# Load dataset
df = pd.read_csv('healthcare_patient_analytics_seaborn.csv')

# Show first 5 rows
df.head()

,patient_id,visit_date,age_group,gender,region,department,treatment_type,visit_type,length_of_stay_days,treatment_cost,recovery_score,readmission_risk
0,1,2022-01-01 00:00:00,31-45,Male,West,General Medicine,Medication,Emergency,5.8,59151.0,59.0,0.12
1,2,2022-01-01 01:00:00,60+,Female,West,Orthopedics,Surgery,Routine,5.1,30272.0,97.0,0.11
2,3,2022-01-01 02:00:00,46-60,Male,South,Pediatrics,Observation,Routine,7.9,67498.0,60.0,0.19
3,4,2022-01-01 03:00:00,31-45,Female,North,Neurology,Medication,Routine,5.0,29896.0,51.0,0.47
4,5,2022-01-01 04:00:00,18-30,Female,North,Neurology,Therapy,Routine,0.0,36208.0,60.0,0.40

#dataset shape

In [6]:
df.shape

(5000, 12)

# coloum heading

In [7]:
df.columns

Index(['patient_id', 'visit_date', 'age_group', 'gender', 'region',
       'department', 'treatment_type', 'visit_type', 'length_of_stay_days',
       'treatment_cost', 'recovery_score', 'readmission_risk'],
      dtype='object')

# data type

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   patient_id           5000 non-null   int64
 1   visit_date           5000 non-null   object
 2   age_group            5000 non-null   object
 3   gender               5000 non-null   object
 4   region               5000 non-null   object
 5   department           5000 non-null   object
 6   treatment_type       5000 non-null   object
 7   visit_type           5000 non-null   object
 8   length_of_stay_days  5000 non-null   float64
 9   treatment_cost       5000 non-null   float64
 10  recovery_score       5000 non-null   float64
 11  readmission_risk     5000 non-null   float64
dtypes: float64(4), int64(1), object(7)
memory usage: 468.9+ KB

#Missing value

In [9]:
df.isnull().sum()

patient_id             0
visit_date             0
age_group              0
gender                 0
region                 0
department             0
treatment_type         0
visit_type             0
length_of_stay_days    0
treatment_cost         0
recovery_score         0
readmission_risk       0
dtype: int64

#Basic Statistics

In [10]:
df.describe()

,patient_id,length_of_stay_days,treatment_cost,recovery_score,readmission_risk
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000
mean,2500.500000,4.059660,54915.471800,74.718800,0.280966
std,1443.520003,1.928847,19481.160487,11.870481,0.157178
min,1.000000,0.000000,746.000000,33.000000,0.010000
25%,1250.750000,2.700000,41244.750000,67.000000,0.160000
50%,2500.500000,4.000000,55123.500000,75.000000,0.260000
75%,3750.250000,5.400000,68012.000000,83.000000,0.380000
max,5000.000000,11.900000,119307.000000,100.000000,0.840000

#  Average Length of Stay

In [11]:
df['length_of_stay_days'].mean()

np.float64(4.05966)

# Avg treatment cost

In [12]:
df['treatment_cost'].mean()

np.float64(54915.4718)

#Department with highest patients

In [14]:
df['department'].value_counts()

department
Orthopedics         1058
Cardiology           995
General Medicine     991
Pediatrics           989
Neurology            967
Name: count, dtype: int64

#Average recovery score

In [15]:
df['recovery_score'].mean()

np.float64(74.7188)